connectInject:
  disruptionBudget:
    enabled: true
  enabled: true
  replicas: 3
  transparentProxy:
    defaultEnabled: true
controller:
  enabled: true
dns:
  enableRedirection: true
  enabled: true
global:
  acls:
    manageSystemACLs: true
  datacenter: eks28n1
  gossipEncryption:
    autoGenerate: true
  image: hashicorp/consul:1.17.0
  # imagePullSecrets:
  # - name: regcred
  # logJSON: true
  name: consul
  peering:
    enabled: true
  tls:
    enableAutoEncrypt: true
    enabled: true
    verify: true
meshGateway:
  enabled: true
  replicas: 3
  service:
    type: ClusterIP
  topologySpreadConstraints: |
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app: {{ template "consul.name" . }}
          release: "{{ .Release.Name }}"
          component: mesh-gateway
server:
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: topology.kubernetes.io/zone
  bootstrapExpect: 5
  replicas: 5
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi
terminatingGateways:
  enabled: true
ui:
  enabled: true
